config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, only: [:edit, :update, :show, :destroy]

  def index
    if params[:search].present?
      @query = params[:search]
      @flats = Flat.where("name LIKE ?", "%#{params[:search]}%")
      # Preventing SQL Injection and Database error for
      # unknown characters
    else
      @flats = Flat.all
    end
  end

  def show; end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render :edit
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def find_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :picture_url, :number_of_guests, :price_per_night)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(flat) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :picture_url %>
    <%= f.input :description %>
    <%= f.input :number_of_guests %>
    <%= f.input :price_per_night %>
    <%= f.button :submit, class: "my-3 btn btn-primary" %>
  <% end %>

app/views/flats/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1 class="my-3">Add a new flat</h1>
        <br>
        <%= render "form", flat: @flat %>
      </div>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
  <div class="container index mt-3">
    <div class="row">
      <div class="col-12">
        <h1>All our flats</h1>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <% if @query %>
          <p>You searched for <strong><%= @query %></strong>. We found <%= @flats.count %> flats out of our <%= Flat.count %> on our website.</p>
        <% else %>
          <p>All <%= Flat.count %> flats.</p>
        <% end %>
      </div>
    </div>

    <div class="row">
      <% @flats.each do |flat| %>
        <div class="col-4">
          <div class="flat-card">
            <div class="flat-card-image" style="background-image: url(<%=flat.picture_url %>)">
            </div>
            <div class="flat-card-content p-3">
              <div class="flat-card-title">
                <h4><%= flat.name%> </h4>
                <p><%= flat.description%></p>
              </div>
              <div class="flex">
                <div class="flex">
                  <i class="fas fa-users mx-2" style="font-size: 18px "></i>
                  <span><%= flat.number_of_guests %></span>
                </div>
                <div class="flex">
                  <i><i class="fas fa-euro-sign mx-1"></i> </i>
                  <%= flat.price_per_night %>
                </div>
              </div>
            </div>
            <div class="flat-card-actions">
              <%= link_to "More Info", flat_path(flat), class: "m-2 more" %>
              <%= link_to "Edit", edit_flat_path(flat), class: "m-2 edit" %>
              <%= link_to "Remove", flat_path(flat), method: :delete,
            data: { confirm: "Are you sure?" }, class: "m-2 remove" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/flats/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1 class="my-3">Add a new flat</h1>
        <br>
        <%= render "form", flat: @flat %>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="map" style="background-image: url(<%=@flat.picture_url %>)"></div>
<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card">
        <h1><%= @flat.name %></h1>
        <h4><%= @flat.address %></h4>
      </div>
      <div class="flat-show-card">
        <h2>A bit more about this flat...</h2>
        <p><%= @flat.description %> </p>
        <div class="map" style="background-image: url('https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/-122.4241,37.78,14.25,0,0/600x600?access_token=pk.eyJ1IjoieWFubmx1Y2tsZWluIiwiYSI6ImNqcnZmeHQwaDAxb2o0NGx2bG1tOWgwNGIifQ.q4zhKOCoH7nDIJNm88leXg')"></div>
      </div>
    </div>
    <div class="col-4">
      <div class="flat-show-card">
        <div>
          <h5><strong>Book this property!</strong></h5>
        </div>
        <form action="">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="inputGroup-sizing-default">From:</span>
            </div>
            <input type="text" class="form-control" placeholder="12/07/2020" aria-label="Default" aria-describedby="inputGroup-sizing-default">
          </div>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="inputGroup-sizing-default">To:</span>
            </div>
            <input type="text" class="form-control" placeholder="18/07/2020" aria-label="Default" aria-describedby="inputGroup-sizing-default">
          </div>
          <input type="submit" value="Book" class="btn btn-success btn-lg btn-block rounded mt-2" style="width: 100%">
        </form>
      </div>
      <div class="flat-show-card">
        <div class="">
          <h4><strong>Details</strong></h4>
        </div>
        <div class="flex">
          <div class="flex">
            <i class="fas fa-users mx-2" style="font-size: 18px "></i>
            <span><%= @flat.number_of_guests %></span>
          </div>
          <div class="flex">
            <i><i class="fas fa-euro-sign mx-1"></i> </i>
            <%= @flat.price_per_night %>
          </div>
        </div>
      </div>
      <div class="flat-show-card">
        <div class="flex-between">
          <div>
            <h5><strong>Share</strong></h5>
          </div>
          <div>
            <i class="fab fa-facebook-square sns"></i>
            <i class="fab fa-twitter-square sns"></i>
            <i class="fab fa-pinterest-square sns"></i>
            <i class="fas fa-envelope-square sns"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="d-flex navbar navbar-expand-lg navbar-light bg-light">
     <%= link_to "Simple Airbnb", flats_path, class: "navbar-brand m-2" %>
      <div class="d-flex">
        <form class="d-flex form-inline ">
          <input class="form-control m-2 p-2" name="search" type="search" placeholder="London" aria-label="Search" value="<%= params[:search] %>">
          <button class="btn btn-outline-success m-2 p-2 px-5" type="submit">Search</button>
        </form>
        <%= link_to "Add Flat", new_flat_path, class: "btn btn-outline-primary m-2 p-2"%>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>